# blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/zwave-js/node-red-contrib-zwave-js/discussions/new
    about: Suggest an idea for this project
    
  - name: Need Help
    url: https://github.com/zwave-js/node-red-contrib-zwave-js/discussions/new
    about: If you just need help, don't hesitate to ask.
